redis.config.common:
   localhostconn:
      host:localhost
      port:6379
      db:0

   41conn:
      host:172.22.69.41
      port:6379
      db:0

redis.config.wechat:
   localhostconn:
      host:localhost
      port:6379
      db:1

   41conn:
      host:172.22.69.41
      port:6379
      db:1

redis.config.colony:
   colony:
      host:172.22.69.35|172.22.69.36|172.22.69.37|172.22.69.38|172.22.69.40|172.22.69.45
      port:6379
      db:0

